"""The two detection signals described in planning.md.

Each signal returns a float in [0, 1]: the probability that the text is
AI-generated, as estimated by that signal alone. They are independent of
each other by design -- one is semantic (LLM judgment), one is structural
(sentence-length variance + punctuation density) -- so scoring.py can
combine them into something more informative than either alone.
"""

import json
import os
import re
import statistics

from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

_groq_client: Groq | None = None


def _get_groq_client() -> Groq | None:
    global _groq_client
    if _groq_client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            return None
        _groq_client = Groq(api_key=api_key)
    return _groq_client


LLM_PROMPT = """You are an assistant helping a creative-writing platform assess \
whether a piece of text was written by a human or generated by an AI language model.

Judge the text on semantic and stylistic coherence: things like whether ideas \
connect the way a person thinking aloud would connect them, whether there are \
small imperfections, digressions, or idiosyncrasies typical of human writing, \
versus the smoothed-over, hedged, listy coherence typical of AI writing.

Respond with ONLY a JSON object, no other text, in this exact form:
{{"ai_probability": <float between 0 and 1, 1.0 = certainly AI-generated, \
0.0 = certainly human-written>, "reasoning": "<one short sentence>"}}

Text to assess:
---
{text}
---
"""


def llm_signal(text: str) -> dict:
    """Ask Groq to judge the text. Returns {"score": float, "reasoning": str}.

    Falls back to a neutral 0.5 score if no API key is configured or the
    call fails -- an external API is a system boundary, so this is the one
    place in the pipeline that needs a defensive fallback.
    """
    client = _get_groq_client()
    if client is None:
        return {"score": 0.5, "reasoning": "no GROQ_API_KEY configured, neutral fallback"}

    try:
        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": LLM_PROMPT.format(text=text)}],
            temperature=0.0,
            max_tokens=200,
        )
        raw = completion.choices[0].message.content.strip()
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        parsed = json.loads(match.group(0) if match else raw)
        score = float(parsed["ai_probability"])
        score = max(0.0, min(1.0, score))
        return {"score": score, "reasoning": parsed.get("reasoning", "")}
    except Exception as exc:
        return {"score": 0.5, "reasoning": f"llm signal error, neutral fallback: {exc}"}


_SENTENCE_SPLIT_RE = re.compile(r"[.!?]+(?:\s+|$)")
_WORD_RE = re.compile(r"[A-Za-z']+")


def stylometric_signal(text: str) -> dict:
    """Structural heuristic signal: sentence-length variance + punctuation density.

    Humans tend to vary sentence length a lot and punctuate inconsistently;
    AI text tends toward uniform sentence length and a "polished" heavy use
    of em dashes / colons / semicolons. Both sub-scores are 0=human-like,
    1=AI-like, then averaged.
    """
    sentences = [s.strip() for s in _SENTENCE_SPLIT_RE.split(text) if s.strip()]
    words = _WORD_RE.findall(text)
    word_count = len(words)

    if len(sentences) < 2 or word_count < 8:
        # Not enough structure to say anything meaningful about variance.
        variance_score = 0.5
    else:
        lengths = [len(_WORD_RE.findall(s)) for s in sentences]
        mean_len = statistics.mean(lengths)
        if mean_len == 0:
            variance_score = 0.5
        else:
            stdev_len = statistics.pstdev(lengths)
            coeff_variation = stdev_len / mean_len
            # cv ~0 (uniform) -> AI-like (1.0); cv >= 0.6 (very variable) -> human-like (0.0)
            variance_score = max(0.0, min(1.0, 1 - (coeff_variation / 0.6)))

    heavy_punct_count = len(re.findall(r"[—;:]", text))
    density_per_100_words = (heavy_punct_count / word_count) * 100 if word_count else 0
    # ~3 heavy-punctuation marks per 100 words maps to a fully AI-like score
    punctuation_score = max(0.0, min(1.0, density_per_100_words / 3.0))

    style_score = 0.5 * variance_score + 0.5 * punctuation_score
    return {
        "score": style_score,
        "sentence_variance_score": variance_score,
        "punctuation_score": punctuation_score,
    }
